# Generated by Django 5.0.4 on 2024-04-15 17:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1924, 5, 10))]),
        ),
    ]
